apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - image: nginx
    imagePullPolicy: Always
    name: nginx
    ports:
    - containerPort: 80
      name: http
      protocol: TCP
    - containerPort: 443
      name: https
  dnsPolicy: ClusterFirst
  nodeName: virtual-kubelet
  #nodeSelector:
  #  kubernetes.io/role: agent
  #  beta.kubernetes.io/os: linux
  #  type: virtual-kubelet
  #tolerations:
  #- key: azure.com/aci
  #  effect: NoSchedule